version: '3'
services:

  db:
    container_name: pg_w_pg_crdt
    build:
        context: .
        dockerfile: ./dockerfiles/db/Dockerfile
    ports:
      - 5582:5432
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=postgres", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sdb
